export const errorName = {
  ADD_TO_CART: 'Add to Cart',
  AUTHORIZATION_ERROR: 'Authorization Error',
  CART_NOT_CREATED: 'Cart Not Created',
  CART_NOT_FOUND: 'Cart Not Found',
  CARTS_NOT_FOUND: 'Carts Not Found',
  EMAIL_NOT_FOUND: 'Email Not Found',
  INVALID_CART_CREDENTIALS: 'Invalid Cart Credentials',
  INVALID_CREDENTIALS: 'Invalid Credentials',
  INVALID_QUANTITY: 'Invalid Quantity',
  MESSAGE_REMOVE: 'Mensaje no encontrado para eliminar',
  MESSAGE_NOT_FOUND: 'Message Not Found',
  GET_MESSAGE_ERROR: 'Get Message Error',
  CREATE_MESSAGE_ERROR: 'Create Message Error',
  DELETE_MESSAGE_ERROR: 'Delete Message Error',
  PRODUCTS_NOT_FOUND: 'Products Not Found',
  PRODUCT_NOT_FOUND: 'Product Not Found',
  PRODUCT_CODE_ALREADY_EXISTS: 'Product Code Already Exists',
  REMOVE_ALL_FROM_CART: 'Remove All from Cart',
  REMOVE_FROM_CART: 'Remove from Cart',
  UPDATED_CART: 'Updated Cart',
  UPDATED_PRODUCTS: 'Updated Products',
  USER_NOT_FOUND: 'User Not Found',
  GET_PRODUCT_ERROR: 'Get Product Error',
  CREATE_PRODUCT_ERROR: 'Create Product Error',
  UPDATE_PRODUCT_ERROR: 'Update Product Error',
  DELETE_PRODUCT_ERROR: 'Delete Product Error',
  SIGNUP_ERROR: 'Signup Error',
  LOGIN_ERROR: 'Login Error',
  SIGNOUT_ERROR: 'Signout Error',
  RESTORE_PASSWORD_ERROR: 'Restore Password Error',
  GITHUB_CALLBACK_ERROR: 'GitHub Callback Error',
  GITHUB_AUTH_ERROR: 'GitHub Auth Error',
  GET_CURRENT_USER_ERROR: 'Get Current User Error',

};

export const errorMessage = {
  ADD_TO_CART: 'Error al agregar producto al carrito',
  AUTHORIZATION_ERROR: 'No tienes los permisos necesarios para acceder a esta página',
  CART_NOT_CREATED: 'Error al crear carrito',
  CART_NOT_FOUND: 'Carrito no encontrado por id',
  CARTS_NOT_FOUND: 'Error al obtener los carritos',
  EMAIL_NOT_FOUND: 'Email no registrado',
  INVALID_CART_CREDENTIALS: 'El ID del carrito en el token no coincide con el ID proporcionado',
  INVALID_CREDENTIALS: 'Acceso no autorizado',
  INVALID_QUANTITY: 'Cantidad inválida',
  MESSAGES_NOT_FOUND: 'Error al obtener los mensajes',
  MESSAGE_NOT_FOUND: 'Mensaje no encontrado',
  GET_MESSAGE_ERROR: 'Error al obtener el mensaje',
  CREATE_MESSAGE_ERROR: 'Error al crear el mensaje',
  DELETE_MESSAGE_ERROR: 'Error al eliminar el mensaje',
  PRODUCTS_NOT_FOUND: 'No se han encontrado productos',
  PRODUCT_NOT_FOUND: 'Producto no encontrado por id',
  PRODUCT_CODE_ALREADY_EXISTS: 'El código de producto ya existe',
  REMOVE_ALL_FROM_CART: 'Error al vaciar carrito',
  REMOVE_FROM_CART: 'Error al eliminar producto del carrito',
  UPDATED_CART: 'Error al actualizar carrito',
  UPDATED_PRODUCTS: 'Producto no actualizado',
  USER_NOT_FOUND: 'Usuario no encontrado',
  GET_PRODUCT_ERROR: 'Error al obtener el producto',
  CREATE_PRODUCT_ERROR: 'Error al crear el producto',
  UPDATE_PRODUCT_ERROR: 'Error al actualizar el producto',
  DELETE_PRODUCT_ERROR: 'Error al eliminar el producto',
  SIGNUP_ERROR: 'Error al registrar usuario',
  LOGIN_ERROR: 'Error al iniciar sesión',
  SIGNOUT_ERROR: 'Error al cerrar sesión',
  RESTORE_PASSWORD_ERROR: 'Error al restaurar la contraseña',
  GITHUB_CALLBACK_ERROR: 'Error en la autenticación de GitHub',
  GITHUB_AUTH_ERROR: 'Error en la autenticación de GitHub',
  GET_CURRENT_USER_ERROR: 'Error al obtener el usuario actual',
};
