export const errorName = {
  ADD_TO_CART: 'Add to Cart',
  AUTHORIZATION_ERROR: 'Authorization Error',
  CART_NOT_CREATED: 'Cart Not Created',
  CART_NOT_FOUND: 'Cart Not Found',
  CARTS_NOT_FOUND: 'Carts Not Found',
  EMAIL_NOT_FOUND: 'Email Not Found',
  INVALID_CART_CREDENTIALS: 'Invalid Cart Credentials',
  INVALID_CREDENTIALS: 'Invalid Credentials',
  INVALID_QUANTITY: 'Invalid Quantity',
  MESSAGE_REMOVE: 'Mensaje no encontrado para eliminar',
  MESSAGE_NOT_FOUND: 'Message Not Found',
  GET_MESSAGE_ERROR: 'Get Message Error',
  CREATE_MESSAGE_ERROR: 'Create Message Error',
  DELETE_MESSAGE_ERROR: 'Delete Message Error',
  PRODUCTS_NOT_FOUND: 'Products Not Found',
  PRODUCT_NOT_FOUND: 'Product Not Found',
  PRODUCT_CODE_ALREADY_EXISTS: 'Product Code Already Exists',
  REMOVE_ALL_FROM_CART: 'Remove All from Cart',
  REMOVE_FROM_CART: 'Remove from Cart',
  UPDATED_CART: 'Updated Cart',
  UPDATED_PRODUCTS: 'Updated Products',
  USER_NOT_FOUND: 'User Not Found',
  GET_PRODUCT_ERROR: 'Get Product Error',
  CREATE_PRODUCT_ERROR: 'Create Product Error',
  UPDATE_PRODUCT_ERROR: 'Update Product Error',
  DELETE_PRODUCT_ERROR: 'Delete Product Error',
  SIGNUP_ERROR: 'Signup Error , Email Already registered',
  LOGIN_ERROR: 'Login Error',
  SIGNOUT_ERROR: 'Signout Error',
  RESTORE_PASSWORD_ERROR: 'Restore Password Error',
  GITHUB_CALLBACK_ERROR: 'GitHub Callback Error',
  GITHUB_AUTH_ERROR: 'GitHub Auth Error',
  GET_CURRENT_USER_ERROR: 'Get Current User Error',
  RESET_TOKEN_NOT_FOUND:'Reset token not found',
  UPDATE_PREMIUM_USER_ERROR:'User not updated',
  UPDATE_USER_ERROR:'Documents not updated',
  USERS_NOT_FOUND:'Users not found',
  DELETE_INACTIVE_USERS_ERROR:'Inactive users not deleted'

};
export const errorMessage = {
  ADD_TO_CART: 'Error adding product to cart',
  AUTHORIZATION_ERROR: 'You do not have the necessary permissions to access this page',
  CART_NOT_CREATED: 'Error creating cart',
  CART_NOT_FOUND: 'Cart not found by ID',
  CARTS_NOT_FOUND: 'Error fetching carts',
  EMAIL_NOT_FOUND: 'Email not registered',
  INVALID_CART_CREDENTIALS: 'Cart ID in the token does not match the provided ID',
  INVALID_CREDENTIALS: 'Unauthorized access',
  INVALID_QUANTITY: 'Invalid quantity',
  MESSAGES_NOT_FOUND: 'Error fetching messages',
  MESSAGE_NOT_FOUND: 'Message not found',
  GET_MESSAGE_ERROR: 'Error fetching the message',
  CREATE_MESSAGE_ERROR: 'Error creating the message',
  DELETE_MESSAGE_ERROR: 'Error deleting the message',
  PRODUCTS_NOT_FOUND: 'No products found',
  PRODUCT_NOT_FOUND: 'Product not found by ID',
  PRODUCT_CODE_ALREADY_EXISTS: 'Product code already exists',
  REMOVE_ALL_FROM_CART: 'Error clearing cart',
  REMOVE_FROM_CART: 'Error removing product from cart',
  UPDATED_CART: 'Error updating cart',
  UPDATED_PRODUCTS: 'Product not updated',
  USER_NOT_FOUND: 'User not found',
  GET_PRODUCT_ERROR: 'Error fetching the product',
  CREATE_PRODUCT_ERROR: 'Error creating the product',
  UPDATE_PRODUCT_ERROR: 'Error updating the product',
  DELETE_PRODUCT_ERROR: 'Error deleting the product',
  SIGNUP_ERROR: 'Error registering user',
  LOGIN_ERROR: 'Error logging in',
  SIGNOUT_ERROR: 'Error logging out',
  RESTORE_PASSWORD_ERROR: 'Error restoring password',
  GITHUB_CALLBACK_ERROR: 'Error in GitHub authentication callback',
  GITHUB_AUTH_ERROR: 'Error in GitHub authentication',
  GET_CURRENT_USER_ERROR: 'Error fetching the current user',
  RESET_TOKEN_NOT_FOUND: 'Reset token not found for password restoration',
  UPDATE_PREMIUM_USER_ERROR: 'Could not update user role',
  UPDATE_USER_ERROR:'Could not update user data',
  DOCUMENTS_NOT_UPDATED:'Missing documents',
  USERS_NOT_FOUND:'No users found',
  DELETE_INACTIVE_USERS_ERROR:'Usuarios inactivos no eliminados'

};
